name: Orca IaC Security Scan

on:
  push:
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  iac_scan_job:
    name: IaC Security Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Scan IaC
        uses: orcasecurity/shiftleft-iac-action@v1
        with:
          api_token: ${{ secrets.ORCA_SECURITY_API_TOKEN }}
          project_key: default
          path: test
          format: sarif
          output: results/
          console_output: cli
          show_annotations: false
      - uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          # Path to SARIF file relative to the root of the repository
          sarif_file: results/iac.sarif
